services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: kiwi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1.5s
      timeout: 5s
      retries: 5
      
  kiwimigrations:
    image: kiwimigrations
    build:
      context: .
      dockerfile: KiwiMigrations/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=kiwi;Username=postgres;Password=password
    depends_on:
      db:
        condition: service_healthy
      
  kiwiapi:
    image: kiwiapi
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: KiwiAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=kiwi;Username=postgres;Password=password
    depends_on:
      - db
      - kiwimigrations
      
  seq:
    image: datalust/seq:latest
    container_name: kiwi-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
        
volumes:
  postgres_data:
