create table if not exists content (
   id bigint generated by default as identity not null,
   date_created timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
   date_updated timestamp with time zone null,
   title text not null,
   description text null,
   content_type text not null,
   constraint content_pkey primary key (id)
);

create table if not exists to_dos (
   id bigint generated by default as identity not null,
   content_id bigint not null,
   date_created timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
   date_updated timestamp with time zone null,
   title text not null,
   description text null,
   is_completed boolean not null default false,
   date_completed timestamp with time zone null,
   constraint to_dos_pkey primary key (id),
   constraint to_dos_content_id_fkey foreign KEY (content_id) references content (id)
);